apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd-bob
spec:
  selector:
    matchLabels:
      app: lnd-bob
  template:
    metadata:
      labels:
        app: lnd-bob
    spec:
      containers:
        - command:
            ["/bin/sh", "-ec", "sleep 1000"]
            # - ./start-lnd.sh
          env:
            - name: CHAIN
            - name: DEBUG
            - name: NETWORK
              value: "regtest"
            - name: RPCPASS
              value: "rpcpass"
            - name: RPCUSER
              value: "rpcuser"
          name: lnd-bob
          image: davidjoos/lnd:v0.14.2-beta
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /rpc
              name: shared
            - mountPath: /root/.lnd
              name: lnd-bob
          ports:
            - containerPort: 10009
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared
        - name: lnd-bob
          persistentVolumeClaim:
            claimName: lnd-bob
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnd-bob
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: lnd-bob
spec:
  type: NodePort
  selector:
    app: lnd-bob
  ports:
    - port: 10009
      targetPort: 10009
      nodePort: 30007
